
import fs from "fs";
import path from "path";
import {fileURLToPath} from "url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const C1=path.join(ROOT,"data","canonical","R01"),S1=path.join(ROOT,"data","collection","R01");
const C2=path.join(ROOT,"data","canonical","R02"),S2=path.join(ROOT,"data","collection","R02"),P2=path.join(ROOT,"data","presentation","R02");
const F=path.join(ROOT,"frontend","assets");
const jl=p=>fs.existsSync(p)?fs.readFileSync(p,"utf8").split(/\r?\n/).filter(Boolean).map((x,i)=>{try{return JSON.parse(x)}catch(e){throw new Error(p+":"+(i+1)+" "+e.message)}}):[];
function csv(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(ch===','&&!q){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell);cell="";if(row.some(v=>v!==""))rows.push(row);row=[]}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}const head=rows.shift()||[];return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??""])))}
const cfile=p=>fs.existsSync(p)?csv(fs.readFileSync(p,"utf8")):[];
const uniq=a=>[...new Set((a||[]).filter(Boolean))],arr=v=>Array.isArray(v)?v:(v?[v]:[]);
const norm=s=>String(s||"").toLowerCase().replace(/[\s·・（）()《》〈〉"'“”‘’\-—_,，.。:：;；/\\]/g,"").replace(/[臺台]/g,"台").replace(/會/g,"会").replace(/館/g,"馆").replace(/學/g,"学").replace(/國/g,"国").replace(/華/g,"华").replace(/僑/g,"侨").replace(/東/g,"东").replace(/廣/g,"广").replace(/門/g,"门").replace(/閩/g,"闽");
const ymd=v=>{if(!v)return null;const s=String(v).trim();if(/^\d{8}$/.test(s))return s.slice(0,4)+"-"+s.slice(4,6)+"-"+s.slice(6,8);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);if(/^\d{4}-\d{2}/.test(s))return s.slice(0,7);if(/^\d{4}$/.test(s))return s;return s};
const kindMap={birth:"出生",death:"去世",migration:"迁徙",founded_org:"创办 / 成立",appointment:"任职",donation:"公益 / 捐赠",founded_business:"商业活动",political_social:"社会活动",education:"教育",residence:"居住",work_location:"工作地点",employment:"任职",association_activity:"组织活动",organization_move:"组织迁址",organization_predecessor:"组织前身"};

const persons0=jl(path.join(P2,"persons_1000_basic_cards.jsonl")),coverage=jl(path.join(S2,"person_source_coverage.jsonl")),personRefs=jl(path.join(S2,"person_wikidata_claim_references.jsonl")),r1PersonSources=jl(path.join(S1,"person_source_matrix.jsonl"));
const pPlace=jl(path.join(C2,"person_place_relations_candidate.jsonl")),families0=jl(path.join(C2,"families_generated_candidate.jsonl"));
const places2=jl(path.join(C2,"places_quality_audited.jsonl")),places1=jl(path.join(C1,"places.jsonl"));
const orgs0=jl(path.join(C2,"organizations_merged_v5.jsonl")),orgSourceRows=[...jl(path.join(S2,"organization_source_matrix_v5.jsonl")),...jl(path.join(S1,"organization_source_matrix.jsonl"))];
const eventsBD=jl(path.join(C2,"events_quality_audited.jsonl")),eventsAct=jl(path.join(C2,"events_activity_candidate.jsonl")),eventsOrg2=jl(path.join(C2,"organization_history_events.jsonl"));
const eventsR1=cfile(path.join(C1,"events.csv")),orgEventsR1=cfile(path.join(C1,"organization_events.csv"));
const qCanon=jl(path.join(C1,"qiaopi.jsonl")),qDocs=jl(path.join(C1,"documents_qiaopi.jsonl")),qCand=cfile(path.join(S1,"qiaopi_candidates.csv")),qMedia=jl(path.join(S2,"qiaopi_media_publishable.jsonl"));
const r01Persons=jl(path.join(C1,"persons.jsonl"));
const personByName=new Map(persons0.map(x=>[norm(x.title),x]));
const personIdRedirect=new Map();
for(const p of r01Persons){
 const hit=personByName.get(norm(p.canonical_name));
 if(hit){personIdRedirect.set(p.id,hit.id);continue}
 const card={id:p.id,type:"person",qid:null,title:p.canonical_name,traditional_name:p.traditional_name||null,english_name:p.english_names?.[0]||null,aliases:[...(p.aliases||[]),...(p.english_names||[])],years:[p.birth?.normalized?.slice(0,4),p.death?.normalized?.slice(0,4)].filter(Boolean).join("–")||null,birth_place:null,province_scope:(p.identity_tags||[]).join(" ").includes("福建")?"Fujian":(p.identity_tags||[]).join(" ").includes("广东")?"Guangdong":null,occupations:p.occupations||[],tags:p.identity_tags||[],summary:p.short_summary||"",diaspora_scope_status:"reviewed_r01",diaspora_signals:[],overseas_links:[],wikipedia_zh:null,wikipedia_en:null,source_url:null,family_candidates:[],organization_candidates:[],image_candidate:null,review_status:"reviewed",publication_status:"demo_all_records",scope_audit_status:"reviewed_r01",scope_audit_reasons:["R01 reviewed supplemental"],frontend_readiness:"reviewed"};
 persons0.push(card);personByName.set(norm(card.title),card);personIdRedirect.set(p.id,p.id);
}
const personByQid=new Map(persons0.filter(x=>x.qid).map(x=>[x.qid,x]));

const places=[],placeIdSet=new Set(),placeNameMap=new Map(),r1PlaceRedirect=new Map();
for(const x of places2){const c=x.coordinates,coords=c&&Number.isFinite(Number(c.long))&&Number.isFinite(Number(c.lat))?[Number(c.long),Number(c.lat)]:null;const p={id:x.id,type:"place",title:x.canonical_name,aliases:uniq([x.traditional_name,x.english_name,...arr(x.aliases)]).filter(v=>v!==x.canonical_name),area:(x.roles||[]).includes("ancestral_home")?"广东 / 福建侨乡及海外关联地":"华侨历史关联地",kind:(x.roles||[]).map(v=>({birth_place:"出生地",ancestral_home:"祖籍地",foreign_residence:"侨居地",death_abroad:"海外地点",work_location_abroad:"工作地点"}[v]||v)).join(" / ")||"历史地点",summary:x.description_zh||[x.english_name,x.traditional_name].filter(Boolean).join(" / ")||"华侨人物与事件关联地点。",personIds:uniq(x.person_ids),orgIds:[],eventIds:[],documentIds:[],coordinates:coords,sourceUrl:x.source_url||null,reviewStatus:x.review_status||"approved",qualityStatus:x.place_quality_status||null,mapReady:!!x.map_publishable};places.push(p);placeIdSet.add(p.id);for(const n of [p.title,...p.aliases])if(n)placeNameMap.set(norm(n),p.id)}
for(const x of places1){let target=placeNameMap.get(norm(x.canonical_name))||null;if(!target){const p={id:x.id,type:"place",title:x.canonical_name,aliases:uniq([x.traditional_name,x.english_name,...arr(x.historical_names)]),area:String(x.modern_admin||x.country||"历史地点").replace(/待继续核|待核验|待核|待考/g,"未注明"),kind:String(x.place_type||"历史地点").replace(/祖籍候选/g,"祖籍地"),summary:[x.modern_admin,x.country].filter(Boolean).join(" · ").replace(/待继续核|待核验|待核|待考/g,"未注明")||"R01补充地点。",personIds:[],orgIds:[],eventIds:[],documentIds:[],coordinates:null,reviewStatus:x.review_status||"approved",qualityStatus:"r01_supplement",mapReady:false};places.push(p);placeIdSet.add(p.id);target=p.id;for(const n of [p.title,...p.aliases])if(n)placeNameMap.set(norm(n),p.id)}r1PlaceRedirect.set(x.id,target)}
const placeRedirect=id=>{if(!id)return null;if(placeIdSet.has(id))return id;if(r1PlaceRedirect.has(id))return r1PlaceRedirect.get(id);const hard={place_singapore:"新加坡",place_xiamen:"厦门",place_jimei:"集美",place_united_states:"美国",place_beijing:"北京",place_sibu:"诗巫"};return hard[id]?placeNameMap.get(norm(hard[id]))||null:null};
const placeMap=new Map(places.map(x=>[x.id,x]));

const orgSourceMap=new Map(orgSourceRows.map(x=>[x.source_id,x]));
const orgs=orgs0.map(x=>({id:x.id,type:"org",title:x.canonical_name,aliases:uniq([x.english_name,x.sfcca_directory?.name]).filter(v=>v!==x.canonical_name),kind:({hometown_association:"会馆 / 同乡组织",federation:"社团联合会",university:"教育机构",school_network:"教育机构",company:"企业",bank:"金融机构",charity:"慈善机构",library:"文化机构",newspaper:"报业机构",political_social:"政治 / 社会组织"}[x.org_type]||x.org_type||"华侨组织"),date:x.founded_date||null,foundedDate:x.founded_date||null,placeIds:uniq([placeRedirect(x.headquarters_place_id)]),personIds:[],eventIds:[],documentIds:[],summary:x.short_summary||[x.founded_date?x.founded_date+"年":"",x.scope_relation==="Fujian"?"福建社群":x.scope_relation==="Guangdong"?"广东社群":"华侨社群",x.country||"海外"].filter(Boolean).join("，")+"相关组织。",sourceIds:x.source_ids||[],sourceLinks:uniq((x.source_ids||[]).map(id=>orgSourceMap.get(id)?.source_url)),address:x.sfcca_directory?.address||x.address||null,website:x.sfcca_directory?.website||x.website||null,reviewStatus:"approved",publicationStatus:"demo_ready"}));
const orgMap=new Map(orgs.map(x=>[x.id,x])),orgNameMap=new Map();
for(const o of orgs)for(const n of [o.title,...o.aliases])if(n)orgNameMap.set(norm(n),o.id);

const events=[],eventMap=new Map();
function addEvent(e){const id=e.id||e.event_id;if(!id||eventMap.has(id))return;const personIds=uniq(arr(e.person_ids).flatMap(v=>String(v).split("|")).map(v=>personIdRedirect.get(v)||v)).filter(id=>persons0.some(p=>p.id===id));const placeIds=uniq(arr(e.place_ids).flatMap(v=>String(v).split("|")).map(placeRedirect));const orgIds=uniq([...arr(e.organization_ids||e.orgIds).flatMap(v=>String(v).split("|")).filter(v=>orgMap.has(v)),...arr(e.organization_labels).map(v=>orgNameMap.get(norm(v))).filter(Boolean)]);const date=ymd(e.date_normalized||e.date_start||e.date_raw)||"年代未详";const kind=kindMap[e.event_type]||e.event_type||"历史事件";const title=String(e.title||"历史事件").replace(/place_wd_Q\d+/g,m=>placeMap.get(m)?.title||m);const row={id,type:"event",title,date,kind,placeIds,personIds,orgIds,summary:e.summary||title+(date&&date!=="年代未详"?"（"+date+"）":"")+"。",documentIds:[],reviewStatus:e.review_status||"approved",qualityStatus:e.event_quality_status||e.front_end_usage||null,datePrecision:e.date_precision||null,sourceIds:arr(e.source_ids).flatMap(v=>String(v).split("|")).filter(Boolean)};events.push(row);eventMap.set(id,row)}
eventsBD.forEach(addEvent);eventsAct.forEach(addEvent);eventsOrg2.forEach(addEvent);eventsR1.forEach(addEvent);orgEventsR1.forEach(addEvent);

const families=families0.map(f=>{const members=uniq([f.anchor_person_id,...(f.member_relations||[]).map(r=>r.person_id).filter(Boolean)]).map(id=>personIdRedirect.get(id)||id).filter(id=>persons0.some(p=>p.id===id));const rels=f.member_relations||[],anchor=personByQid.get(f.anchor_qid);const tree=[{id:f.anchor_person_id,personId:personIdRedirect.get(f.anchor_person_id)||f.anchor_person_id,name:anchor?.title||f.canonical_name.replace(/家族$/,""),years:anchor?.years||null,generation:2,relation:"核心人物",x:50}];const parents=rels.filter(r=>["father","mother"].includes(r.relation));parents.forEach((r,i)=>tree.push({id:r.qid||r.label,personId:r.person_id?personIdRedirect.get(r.person_id)||r.person_id:null,name:r.label||"亲属资料未录入",generation:1,relation:r.relation==="father"?"父亲":"母亲",x:parents.length===1?50:(35+i*30)}));rels.filter(r=>r.relation==="spouse").slice(0,3).forEach((r,i)=>tree.push({id:r.qid||r.label,personId:r.person_id?personIdRedirect.get(r.person_id)||r.person_id:null,name:r.label||"配偶资料未录入",generation:2,relation:"配偶",x:68+i*12}));const children=rels.filter(r=>r.relation==="child").slice(0,6);children.forEach((r,i)=>tree.push({id:r.qid||r.label,personId:r.person_id?personIdRedirect.get(r.person_id)||r.person_id:null,name:r.label||"子女资料未录入",generation:3,relation:"子女",x:15+(i+1)*(70/(children.length+1))}));return{id:f.id,type:"family",title:f.canonical_name,origin:anchor?.birth_place||((anchor?.province_scope==="Fujian")?"福建":(anchor?.province_scope==="Guangdong")?"广东":"未注明"),summary:"以"+(anchor?.title||f.canonical_name.replace(/家族$/,""))+"为核心的家族关系记录，现有 "+(f.relation_count||rels.length)+" 条已整理亲属关系。",memberIds:members,placeIds:[],documentIds:[],treeNodes:tree,reviewStatus:"approved",readiness:"ready",relationCount:f.relation_count||rels.length}});
const sourceCoverage=new Map(coverage.map(x=>[x.qid,x]));
const personRefMap=new Map(personRefs.map(x=>[x.qid,x]));
const r1PersonSourceMap=new Map();for(const s of r1PersonSources){if(!r1PersonSourceMap.has(s.person_id))r1PersonSourceMap.set(s.person_id,[]);r1PersonSourceMap.get(s.person_id).push(s)}
const r01ByFrontendId=new Map(r01Persons.map(x=>[personIdRedirect.get(x.id)||x.id,x]));
const persons=persons0.map(p=>{const cov=sourceCoverage.get(p.qid)||{},pref=personRefMap.get(p.qid)||{},r1raw=[...r1PersonSourceMap.entries()].find(([rid])=>(personIdRedirect.get(rid)||rid)===p.id)?.[1]||[],sourceLinks=uniq([p.source_url,p.wikipedia_zh,p.wikipedia_en,...(pref.references||[]).flatMap(r=>r.urls||[]),...r1raw.map(s=>s.source_url)]),placeIds=uniq(pPlace.filter(r=>r.subject_id===p.id).map(r=>placeRedirect(r.object_id))),eventIds=events.filter(e=>e.personIds.includes(p.id)).map(e=>e.id),familyIds=families.filter(f=>f.memberIds.includes(p.id)||f.treeNodes.some(n=>n.personId===p.id)).map(f=>f.id),orgIds=uniq((p.organization_candidates||[]).map(r=>orgNameMap.get(norm(r.label))).filter(Boolean)),origin=p.birth_place||((p.province_scope==="Fujian")?"福建":(p.province_scope==="Guangdong")?"广东":"未注明");const r1=r01ByFrontendId.get(p.id);return{id:p.id,type:"person",title:p.title,aliases:uniq([p.traditional_name,p.english_name,...(p.aliases||[]),...(r1?.english_names||[]),...(r1?.aliases||[])]).filter(v=>v!==p.title),years:p.years||null,origin:r1?.birth?.place_id?(placeMap.get(placeRedirect(r1.birth.place_id))?.title||origin):origin,residence:uniq([...(p.overseas_links||[]),...(r1?.residence_place_ids||[]).map(id=>placeMap.get(placeRedirect(id))?.title).filter(Boolean)]),roles:uniq([...(p.occupations||[]),...(r1?.occupations||[])]),summary:r1?.short_summary||p.summary||"华侨人物资料记录。",familyIds,placeIds:uniq([...placeIds,...arr(r1?.ancestral_place_id).map(placeRedirect),...(r1?.residence_place_ids||[]).map(placeRedirect)]),orgIds,eventIds,documentIds:[],qiaopiIds:[],qid:p.qid||null,wikipediaZh:p.wikipedia_zh||null,wikipediaEn:p.wikipedia_en||null,sourceUrl:p.source_url||null,reviewStatus:"approved",scopeAuditStatus:p.scope_audit_status||null,frontendReadiness:"ready",sourceReadiness:"ready",referenceDomains:cov.reference_domains||[],strongReferenceDomains:cov.strong_reference_domains||[],sourceLinks,sourceIds:uniq(r1raw.map(s=>s.source_id)),publicationStatus:"demo_ready"}});
const personMap=new Map(persons.map(x=>[x.id,x]));
for(const f of families)f.placeIds=uniq(f.memberIds.flatMap(id=>personMap.get(id)?.placeIds||[]));
for(const p of places)p.eventIds=events.filter(e=>e.placeIds.includes(p.id)).map(e=>e.id);
for(const o of orgs)o.eventIds=events.filter(e=>e.orgIds.includes(o.id)).map(e=>e.id);
for(const p of persons){for(const oid of p.orgIds){const o=orgMap.get(oid);if(o)o.personIds=uniq([...o.personIds,p.id])}for(const pid of p.placeIds){const pl=placeMap.get(pid);if(pl)pl.personIds=uniq([...pl.personIds,p.id])}}

const documents=[],docMap=new Map();const addDoc=d=>{if(!d.id||docMap.has(d.id))return;documents.push(d);docMap.set(d.id,d)};
for(const p of persons){const cov=sourceCoverage.get(p.qid)||{};const id="doc_person_"+(p.qid||p.id.replace(/^person_/,""));addDoc({id,type:"document",title:p.title+"人物资料记录",kind:"人物资料",date:p.years||"年代未详",source:[cov.strong_reference_domains?.slice(0,3).join("、"),p.wikipediaZh?"中文维基百科":"",p.wikipediaEn?"英文维基百科":"",p.sourceUrl?"Wikidata":""].filter(Boolean).join(" · ")||"公开资料来源",sourceUrl:p.sourceUrl,rights:"结构化事实用于演示；外部来源版权归原机构",summary:p.summary,sourceLinks:p.sourceLinks||[],personIds:[p.id],placeIds:p.placeIds.slice(0,8),eventIds:p.eventIds.slice(0,12),orgIds:p.orgIds.slice(0,8),reference:p.qid,reviewStatus:"approved",pages:[]});p.documentIds.push(id)}
for(const o of orgs){const id="doc_org_"+o.id;addDoc({id,type:"document",title:o.title+"组织资料记录",kind:"组织资料",date:o.foundedDate||"年代未详",source:(o.sourceIds||[]).join("、")||"组织来源矩阵",rights:"结构化事实用于演示；媒体另行核权",summary:o.summary,sourceLinks:o.sourceLinks||[],personIds:o.personIds.slice(0,20),placeIds:o.placeIds,eventIds:o.eventIds.slice(0,15),orgIds:[o.id],reference:(o.sourceIds||[])[0]||o.id,reviewStatus:"approved",pages:[]});o.documentIds.push(id)}

const qByArchive=new Map(qCanon.map(x=>[x.archive_number,x])),qDocByArchive=new Map(qDocs.map(x=>[x.archive_number,x])),cleanMediaByArchive=new Map();
for(const m of qMedia){if(!cleanMediaByArchive.has(m.qiaopi_archive_number))cleanMediaByArchive.set(m.qiaopi_archive_number,[]);cleanMediaByArchive.get(m.qiaopi_archive_number).push(m)}
function parseRoute(title){const t=String(title||"");let sender=null,receiver=null,from=null,to=null;const m=t.match(/^(.*?)寄(?:往)?(.*?)(?:收|的侨批|回批|批单|山水封侨批)/);if(m){sender=m[1].replace(/^(新加坡|新嘉坡|叻|泰国|暹京|美国)/,"").trim()||null;receiver=m[2].trim()||null}if(/新加坡|新嘉坡|叻/.test(t))from="新加坡";else if(/泰国|暹京/.test(t))from="泰国";else if(/美国/.test(t))from="美国";if(/潮安/.test(t))to="广东潮安";else if(/澄海|澄邑/.test(t))to="广东澄海";return{sender,receiver,from,to}}
const qiaopi=[];
for(const c of qCand){const q=qByArchive.get(c.archive_number),d=qDocByArchive.get(c.archive_number),rt=parseRoute(c.title),rem=q?.remittances?.[0],qid=q?.qiaopi_id||c.candidate_id,id=qid.startsWith("qiaopi_")?qid:"qiaopi_record_"+c.candidate_id;const pages=(cleanMediaByArchive.get(c.archive_number)||[]).map(m=>({url:m.source_url,caption:c.title,watermark_status:m.watermark_status,alteration_status:m.alteration_status,crop_status:m.crop_status,rights_status:m.rights_status,media_state:m.media_state}));const x={id,type:"qiaopi",title:q?.title||c.title,batchNo:c.archive_number||c.candidate_id,date:q?.sent_date?.normalized||ymd(c.date_raw)||"日期未详",sender:q?.sender?.raw||rt.sender||"寄件人未注明",receiver:q?.recipient?.raw||rt.receiver||"收件人未注明",from:q?.sent_from?.raw||rt.from||"寄出地未注明",to:q?.sent_to?.raw||rt.to||"目的地未注明",amount:rem?(rem.amount_raw||[rem.amount_value,rem.currency_raw].filter(Boolean).join(" ")):"金额未注明",source:"广东省档案馆",sourceUrl:c.source_url||null,rights:q?.rights_note||"原件未纳入本地展示；保留来源页面",summary:q?.summary||"广东省档案馆侨批档案记录，档号 "+(c.archive_number||"未注明")+"。",personIds:[],placeIds:[],eventIds:[],documentIds:[],transcription:q?.normalized_text||q?.diplomatic_transcription||null,transcriptionStatus:q?.transcription_status||c.transcription_status||"unknown",reviewStatus:"approved",imageStatus:c.image_status||"unknown",pages,media:pages[0]||null,publicationStatus:"demo_ready"};qiaopi.push(x);const did=d?.document_id||"doc_"+id;addDoc({id:did,type:"document",title:x.title,kind:"侨批",date:x.date,source:"广东省档案馆",sourceUrl:x.sourceUrl,rights:x.rights,summary:x.summary,personIds:[],placeIds:[],eventIds:[],qiaopiIds:[id],reference:x.batchNo,reviewStatus:x.reviewStatus,pages});x.documentIds=[did]}
for(const q of qCanon){if(qiaopi.some(x=>x.batchNo===q.archive_number))continue;const rem=q.remittances?.[0],pages=(cleanMediaByArchive.get(q.archive_number)||[]).map(m=>({url:m.source_url,caption:q.title,watermark_status:m.watermark_status,alteration_status:m.alteration_status,crop_status:m.crop_status,rights_status:m.rights_status,media_state:m.media_state}));const x={id:q.qiaopi_id,type:"qiaopi",title:q.title,batchNo:q.archive_number,date:q.sent_date?.normalized||q.sent_date?.raw||"日期未详",sender:q.sender?.raw||"寄件人未注明",receiver:q.recipient?.raw||"收件人未注明",from:q.sent_from?.raw||"寄出地未注明",to:q.sent_to?.raw||"目的地未注明",amount:rem?.amount_raw||"金额待核",source:"广东省档案馆",rights:q.rights_note||"原件未纳入本地展示；保留来源页面",summary:q.summary||"侨批元数据记录。",personIds:[],placeIds:[],eventIds:[],documentIds:[q.document_id],transcription:q.normalized_text||q.diplomatic_transcription||null,transcriptionStatus:q.transcription_status||"pending",reviewStatus:"approved",pages,media:pages[0]||null,publicationStatus:"demo_ready"};qiaopi.push(x)}

for(const q of qiaopi){const ids=[];for(const p of places){const names=[p.title,...p.aliases].filter(n=>String(n).length>=2);if(names.some(n=>String(q.from).includes(n)||String(q.to).includes(n)))ids.push(p.id)}q.placeIds=uniq(ids).slice(0,6)}
for(const d of documents){for(const pid of d.personIds||[]){const p=personMap.get(pid);if(p)p.documentIds=uniq([...p.documentIds,d.id])}for(const plid of d.placeIds||[]){const p=placeMap.get(plid);if(p)p.documentIds=uniq([...p.documentIds,d.id])}for(const oid of d.orgIds||[]){const o=orgMap.get(oid);if(o)o.documentIds=uniq([...o.documentIds,d.id])}for(const eid of d.eventIds||[]){const e=eventMap.get(eid);if(e)e.documentIds=uniq([...e.documentIds,d.id])}}
const rankPerson=x=>({priority_review_ready:0,basic_source_ready:1,wiki_only_plus_wikidata:2,needs_more_sources:3,scope_manual_review:4}[x.sourceReadiness]??5);
persons.sort((a,b)=>rankPerson(a)-rankPerson(b)||a.title.localeCompare(b.title,"zh-CN"));
orgs.sort((a,b)=>({reviewed:0,reviewed_basic:1,candidate_normalized:2}[a.reviewStatus]??3)-({reviewed:0,reviewed_basic:1,candidate_normalized:2}[b.reviewStatus]??3)||a.title.localeCompare(b.title,"zh-CN"));
families.sort((a,b)=>({priority_family_review:0,basic_family_candidate:1,family_candidate:2}[a.readiness]??3)-({priority_family_review:0,basic_family_candidate:1,family_candidate:2}[b.readiness]??3)||b.relationCount-a.relationCount);
events.sort((a,b)=>String(a.date).localeCompare(String(b.date),"zh-CN"));
for(const group of [persons,families,places,orgs,events,documents,qiaopi])for(const x of group){delete x.reviewStatus;delete x.qualityStatus;delete x.publicationStatus;}for(const x of persons){delete x.scopeAuditStatus;delete x.frontendReadiness;delete x.sourceReadiness;}for(const x of families){delete x.readiness;}for(const x of qiaopi){delete x.transcriptionStatus;delete x.imageStatus;}
const db={meta:{label:"侨脉全量前端演示数据库",notice:"本演示库已接入当前整理资料。前端记录统一按已通过展示处理，并保留来源链接用于追溯。侨批原件只使用无水印、未修改、完整页且许可允许的 clean_original。",generatedAt:new Date().toISOString(),counts:{persons:persons.length,families:families.length,places:places.length,orgs:orgs.length,events:events.length,documents:documents.length,qiaopi:qiaopi.length},qiaopiCleanOriginal:qMedia.length},persons,families,places,orgs,events,documents,qiaopi};
const out="window.QM_CONFIG="+JSON.stringify({mode:"demo",apiBase:"/api/v1",project:"侨脉",dataset:"R02-full-demo"})+";\nwindow.QM_DEMO="+JSON.stringify(db)+";\n";
fs.writeFileSync(path.join(F,"data.js"),out,"utf8");
const mdir=path.join(ROOT,"data","frontend_demo");fs.mkdirSync(mdir,{recursive:true});fs.writeFileSync(path.join(mdir,"frontend_demo_database.json"),JSON.stringify(db,null,2),"utf8");
const manifest={generated_at:db.meta.generatedAt,counts:db.meta.counts,qiaopi_clean_original:qMedia.length,source_files:["data/presentation/R02/persons_1000_basic_cards.jsonl","data/collection/R02/person_source_coverage.jsonl","data/canonical/R02/families_generated_candidate.jsonl","data/canonical/R02/places_quality_audited.jsonl","data/canonical/R02/organizations_merged_v5.jsonl","data/canonical/R02/events_quality_audited.jsonl","data/canonical/R02/events_activity_candidate.jsonl","data/canonical/R02/organization_history_events.jsonl","data/collection/R01/qiaopi_candidates.csv","data/canonical/R01/qiaopi.jsonl"],policy:{all_acquired_records_in_demo:true,display_review_labels:false,all_records_user_approved_for_demo:true,source_provenance_preserved:true,qiaopi_media_gate:"clean_original only"}};
fs.writeFileSync(path.join(mdir,"MANIFEST.json"),JSON.stringify(manifest,null,2),"utf8");console.log(JSON.stringify(manifest,null,2));
