import fs from "fs";import path from "path";import {fileURLToPath} from "url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const S=path.join(ROOT,"data","collection","R02");
const C=path.join(ROOT,"data","canonical","R02");
const P=path.join(ROOT,"data","presentation","R02");
fs.mkdirSync(P,{recursive:true});
const jl=p=>fs.readFileSync(p,"utf8").split(/\r?\n/).filter(Boolean).map(JSON.parse);
const people=jl(path.join(S,"person_candidates_1000_scope_audited.jsonl"));
const events=jl(path.join(C,"events_quality_audited.jsonl"));
const places=jl(path.join(C,"places_quality_audited.jsonl"));
const keepPeople=people.filter(x=>["keep_high","keep_medium"].includes(x.scope_audit_status));
const manualPeople=people.filter(x=>x.scope_audit_status==="manual_review");
const blockedPeople=people.filter(x=>x.scope_audit_status==="likely_out_of_scope");
const feEvents=events.filter(x=>x.event_quality_status==="front_end_candidate");
const mapPlaces=places.filter(x=>x.place_quality_status==="map_ready");
const textPlaces=places.filter(x=>x.place_quality_status==="text_ready_no_coordinates");
const write=(name,arr)=>fs.writeFileSync(path.join(P,name),arr.map(x=>JSON.stringify(x)).join("\n")+(arr.length?"\n":""),"utf8");
write("persons_scope_passed_candidates.jsonl",keepPeople);
write("persons_manual_review.jsonl",manualPeople);
write("persons_scope_blocked.jsonl",blockedPeople);
write("events_frontend_candidates.jsonl",feEvents);
write("places_map_ready.jsonl",mapPlaces);
write("places_text_ready.jsonl",textPlaces);
const summary={people_scope_passed:keepPeople.length,people_manual_review:manualPeople.length,people_scope_blocked:blockedPeople.length,events_frontend_candidates:feEvents.length,places_map_ready:mapPlaces.length,places_text_ready:textPlaces.length};
fs.writeFileSync(path.join(P,"R02_filtered_snapshots_summary.json"),JSON.stringify(summary,null,2),"utf8");
console.log(JSON.stringify(summary,null,2));
