/* Run with NODE_PATH pointing to the bundled Playwright dependency directory. */
const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/frontend-redesign');
const base=process.env.QM_TEST_URL||'http://127.0.0.1:8767/';
const routes=['index','person','family','place','event','org','archive','qiaopi','research','search','qiaopi-workbench'];
const report={date:'2026-10-08',base,matrix:[],interactions:[],offline:[],failures:[]};
async function main(){
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),page=await browser.newPage();
 let runtimeErrors=[],resourceErrors=[];
 page.on('pageerror',e=>runtimeErrors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')runtimeErrors.push(msg.text())});page.on('response',r=>{if(r.status()>=400)resourceErrors.push(r.status()+' '+r.url())});
 async function ready(url){await page.goto(url);await page.waitForFunction(()=>document.body.dataset.page==='workbench'?!!document.querySelector('[data-ocr-run]'):document.body.dataset.ready==='true');await page.locator('.site-nav').waitFor();}
 async function check(name,fn){try{await fn();report.interactions.push({name,passed:true})}catch(e){report.interactions.push({name,passed:false,error:e.message});report.failures.push(name+': '+e.message)}}
 for(const width of [1440,1672,1920,1024,390]){
  await page.setViewportSize({width,height:width===390?844:941});
  for(const route of routes){runtimeErrors=[];resourceErrors=[];await ready(base+route+'.html');
   await page.locator('img').evaluateAll(xs=>Promise.all(xs.map(x=>x.complete?Promise.resolve():new Promise(r=>{x.onload=x.onerror=r;setTimeout(r,2000)}))));
   const state=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,failed:!!document.querySelector('.error-card'),broken:[...document.images].filter(x=>x.naturalWidth===0).map(x=>x.src),maps:document.querySelectorAll('[data-map] svg').length}));
   const pass=state.scroll<=state.client+1&&!state.failed&&!state.broken.length&&!runtimeErrors.length&&!resourceErrors.length;const row={route,width,pass,...state,runtimeErrors:[...runtimeErrors],resourceErrors:[...resourceErrors]};report.matrix.push(row);if(!pass)report.failures.push(route+' '+width+': '+JSON.stringify(row));
   if((width===1672||width===390)&&!['search','qiaopi-workbench'].includes(route))await page.screenshot({path:path.join(out,route+'-'+width+'.png'),fullPage:true});
  }
 }
 await page.setViewportSize({width:1672,height:941});
 await check('人物检索、选中态和详情联动',async()=>{await ready(base+'person.html');await page.locator('[data-list-search]').fill('李光前');assert.equal(await page.locator('[data-record-id]').count(),1);await page.locator('[data-record-id]').click();assert.match(await page.locator('.person-dossier h2').innerText(),/李光前/);assert.match(page.url(),/p-li-guangqian/)});
 await check('组合筛选和无结果状态',async()=>{await ready(base+'person.html');await page.locator('[data-filter]').selectOption('广东');assert.equal(await page.locator('[data-record-id]').count(),3);await page.locator('[data-list-search]').fill('无此人物xyz');assert.equal(await page.locator('[data-record-id]').count(),0);assert.match(await page.locator('[data-record-list]').innerText(),/没有匹配/)});
 await check('家族三代、单代和人物节点',async()=>{await ready(base+'family.html');await page.locator('[data-generation="3"]').click();assert.equal(await page.locator('.tree-node').count(),4);await page.locator('[data-generation="1"]').click();assert.equal(await page.locator('.tree-node').count(),2);await page.locator('[data-generation="2"]').click();assert.match(await page.locator('.tree-node[href]').getAttribute('href'),/person.html/)});
 await check('家族迁徙筛选',async()=>{await page.getByLabel('主要迁徙地',{exact:true}).selectOption('美国');assert.equal(await page.locator('[data-record-id]').count(),0);await page.getByLabel('主要迁徙地',{exact:true}).selectOption('新加坡');assert.equal(await page.locator('[data-record-id]').count(),2)});
 await check('地点列表、地图 zoom 和中国视图',async()=>{await ready(base+'place.html');await page.locator('[data-place-id="pl-xiamen"]').click();assert.equal(await page.locator('[data-place-detail] h2').innerText(),'厦门');const before=await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('[data-map]')).getOption().geo[0].zoom);await page.getByLabel('放大地图',{exact:true}).click();const after=await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('[data-map]')).getOption().geo[0].zoom);assert(after>before);await page.locator('[data-map-scope="china"]').click();assert.equal(await page.locator('[data-map-scope="china"]').getAttribute('class'),'active')});
 await check('地图真实节点点击更新地点',async()=>{await ready(base+'place.html');const point=await page.evaluate(()=>{const dom=document.querySelector('[data-map]'),chart=echarts.getInstanceByDom(dom);const [x,y]=chart.convertToPixel({geoIndex:0},[-122.42,37.77]);const r=dom.getBoundingClientRect();return{x:r.x+x,y:r.y+y}});await page.mouse.click(point.x,point.y);assert.equal(await page.locator('[data-place-detail] h2').innerText(),'旧金山')});
 await check('事件类型筛选、清除和排序',async()=>{await ready(base+'event.html');await page.locator('[data-event-kind="汇款"]').click();assert.equal(await page.locator('[data-event-id]').count(),1);await page.locator('[data-event-kind="汇款"]').click();assert.equal(await page.locator('[data-event-id]').count(),9);await page.locator('[data-event-sort]').selectOption('desc');await page.locator('[data-event-id]').first().click();assert.equal(await page.locator('[data-event-detail] h2').innerText(),await page.locator('[data-event-id]').first().locator('h3').innerText())});
 await check('组织类型与地区组合筛选',async()=>{await ready(base+'org.html');assert.equal(await page.locator('.org-dossier h2').innerText(),'厦门大学');await page.getByLabel('类型',{exact:true}).selectOption('教育机构');assert.equal(await page.locator('[data-record-id]').count(),2);await page.getByLabel('地区',{exact:true}).selectOption('美国');assert.equal(await page.locator('[data-record-id]').count(),0)});
 await check('档案分面筛选和三个 tab',async()=>{await ready(base+'archive.html');await page.locator('[data-facet="kind"][value="侨批"]').check();assert.equal(await page.locator('[data-record-id]').count(),1);await page.locator('[data-record-id]').click();await page.locator('[data-archive-tab="metadata"]').click();assert.match(await page.locator('[role="tabpanel"]').innerText(),/许可/);await page.locator('[data-archive-tab="relations"]').click();assert.match(await page.locator('[role="tabpanel"]').innerText(),/关联人物/);await page.locator('[data-archive-tab="preview"]').click();assert.equal(await page.locator('.viewer').count(),1)});
 await check('档案收藏持久化',async()=>{await ready(base+'archive.html?id=d-cjk-profile');await page.evaluate(()=>localStorage.removeItem('qm-bookmarks'));await page.reload();await page.locator('[data-bookmark]').click();await page.reload();await page.locator('[data-bookmark]').waitFor();assert.equal(await page.locator('[data-bookmark]').getAttribute('aria-pressed'),'true')});
 await check('侨批阅读器缩放、全屏和无图状态',async()=>{await ready(base+'qiaopi.html?id=q-001');await page.getByLabel('放大影像',{exact:true}).click();assert.match(await page.locator('[data-viewer-page]').innerText(),/125%/);await page.getByLabel('全屏阅读',{exact:true}).click();assert.equal(await page.locator('dialog .viewer img').count(),1);await page.locator('dialog [data-close]').click();await page.locator('[data-record-id="q-002"]').click();assert.equal(await page.locator('.viewer img').count(),0);assert.match(await page.locator('.viewer').innerText(),/暂无可公开原件/)});
 await check('阅读器翻页与媒体准入门槛',async()=>{await page.evaluate(()=>{const demo={id:'test-multipage',type:'document',title:'阅读器测试',pages:[{url:'assets/demo-letter.svg',caption:'第一页'},{url:'assets/media/seal.svg',caption:'第二页'}]};QM.dialog('阅读器测试',QM_VIEWER.element(demo))});await page.locator('dialog [data-viewer-next]').click();assert.match(await page.locator('dialog [data-viewer-page]').innerText(),/2 \/ 2/);await page.locator('dialog [data-viewer-prev]').click();assert.match(await page.locator('dialog [data-viewer-page]').innerText(),/1 \/ 2/);await page.locator('dialog [data-close]').click();const gate=await page.evaluate(()=>QM_VIEWER.pages({type:'qiaopi',id:'gate-test',pages:[{url:'assets/demo-letter.svg',watermark_status:'present'}]}).length);assert.equal(gate,0)});
 await check('人物对比和其余三个分析入口',async()=>{await ready(base+'research.html');await page.locator('[data-analysis="compare"]').click();await page.locator('[data-compare-select="0"]').selectOption('p-ronghong');assert.match(await page.locator('[data-compare-body="0"]').innerText(),/1828/);await page.locator('dialog [data-close]').click();for(const a of ['migration','qiaopi','network']){await page.locator('[data-analysis="'+a+'"]').click();assert.equal(await page.locator('dialog').count(),1);await page.locator('dialog [data-close]').click()}});
 await check('全库检索、类型切换与无结果',async()=>{await ready(base+'search.html?q=陈嘉庚');assert((await page.locator('.search-result').count())>0);await page.locator('[data-search-type="person"]').click();await page.waitForFunction(()=>document.querySelectorAll('.search-result').length===1);assert.equal(await page.locator('.search-result').count(),1);await page.locator('[data-query]').fill('nothing-xyz');await page.locator('[data-search-form]').press('Enter');await page.waitForFunction(()=>document.querySelector('[data-search-results]').textContent.includes('未找到'));assert.equal(await page.locator('.search-result').count(),0)});
 await check('工作台保留 OCR 与提取演示',async()=>{await ready(base+'qiaopi-workbench.html');await page.locator('[data-ocr-run]').click();await page.locator('[data-extract]').click();assert.equal(await page.locator('[data-field="sender"]').inputValue(),'陈某（演示）')});
 await page.setViewportSize({width:390,height:844});
 await check('移动端档案列表与详情切换',async()=>{await ready(base+'archive.html');assert.equal(await page.locator('[data-archive-detail]').isVisible(),false);await page.locator('[data-record-id]').first().click();assert.equal(await page.locator('[data-archive-detail]').isVisible(),true);await page.locator('[data-back-list]').click();assert.equal(await page.locator('[data-archive-list]').isVisible(),true)});
 await check('移动端侨批列表与详情切换',async()=>{await ready(base+'qiaopi.html');await page.locator('[data-record-id]').first().click();assert.equal(await page.locator('[data-detail]').isVisible(),true);await page.locator('[data-back-list]').click();assert.equal(await page.locator('.directory-side').isVisible(),true)});
 await check('移动端导航展开',async()=>{await page.locator('.nav-toggle').click();assert.equal(await page.locator('.nav-toggle').getAttribute('aria-expanded'),'true')});
 await page.setViewportSize({width:1440,height:941});
 // Deny all network connections for direct file:// delivery checks.
 await page.route(/^https?:/,r=>r.abort());
 for(const route of routes.filter(x=>x!=='qiaopi-workbench')){runtimeErrors=[];await ready(pathToFileURL(path.join(root,'frontend',route+'.html')).href);const ok=await page.locator('.error-card').count()===0&&!runtimeErrors.length;report.offline.push({route,pass:ok,maps:await page.locator('[data-map] svg').count(),errors:[...runtimeErrors]});if(!ok)report.failures.push('offline '+route)}
 await page.unroute(/^https?:/);
 await check('Backend 服务失败不会静默回落 Demo',async()=>{await page.route('**/assets/data.js*',async route=>{let s=fs.readFileSync(path.join(root,'frontend/assets/data.js'),'utf8');s=s.replace('mode:"demo"','mode:"backend"');await route.fulfill({body:s,contentType:'text/javascript'})});await ready(base+'index.html');assert.equal(await page.locator('.error-card').count(),1);assert.equal(await page.locator('.home-stat').count(),0);await page.unroute('**/assets/data.js*')});
 await browser.close();report.pass=report.failures.length===0;fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,matrix:report.matrix.length,interactions:report.interactions.length,offline:report.offline.length,failures:report.failures},null,2));if(!report.pass)process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1});
